### PR TITLE
hotfix/createBracketMethod -> master

### PR DESCRIPTION
**Pull request by mzroth**
This change is [Reviewable](https://reviewable.io/reviews/romrell4/bracket-challenge-ws/9)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[test/tests.py, line 42 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9#-KsFis18VSgwguFI0BGp:-KsFis19nK8yNmZoVLIv:b6zxm51) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/8a69036a685300bb0b60e9d4fda331a5b1fea4ef/test/tests.py#L42)):*
> ```Python
> def create_bracket(rounds, only_first_round, commit_to_database = True, player_ids = None):
> 
>     if player_ids is None:
> ```

Add comment here

---

*[test/tests.py, line 52 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9#-KsFiqgFD06K00oHzHy7:-KsFiqgFD06K00oHzHy8:b6zxm51) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/8a69036a685300bb0b60e9d4fda331a5b1fea4ef/test/tests.py#L52)):*
> ```Python
>             player_ids.append(player["player_id"])
>     else:
>         assert len(player_ids) == int(math.pow(2, rounds))
> ```

Add comment here

---

*[test/tests.py, line 151 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9#-KsFjKn_zgZTpt37uoK8:-KsFjKn_zgZTpt37uoK9:b-kfu1ny) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/8a69036a685300bb0b60e9d4fda331a5b1fea4ef/test/tests.py#L151)):*
> ```Python
> 
>         # change this number to change the size of a new tournament
>         rounds = 3
> ```

Change back

---

*[test/tests.py, line 172 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9#-KsFjeXGAi9d_8Jh47Wv:-KsFjeXGAi9d_8Jh47Ww:b-q0ybtc) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/8a69036a685300bb0b60e9d4fda331a5b1fea4ef/test/tests.py#L172)):*
> ```Python
>             assert len(body["rounds"]) == rounds
>             for round in range(rounds):
>                 assert len(body["rounds"][round]) == int(len(player_ids) / math.pow(2, round + 1))
> ```

How many times is this used?

---

*[test/tests.py, line 292 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9#-KsFjrqHA-jP_fqfQWok:-KsFjrqHA-jP_fqfQWol:bn7wk2b) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/e1fad372666ca3eeedc206483fb0e96c4f885603/test/tests.py#L292)):*
> ```Python
> 
>             # test with master
>             bracket = {"name": "test"}
> ```

Put this back and fix test

---

*[test/tests.py, line 365 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9#-KsFk-LfYHn668JWq-gr:-KsFk-LfYHn668JWq-gs:b-qfdnhu) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/8a69036a685300bb0b60e9d4fda331a5b1fea4ef/test/tests.py#L365)):*
> ```Python
>         rounds = 2
> 
>         # Testing a  master bracket (first round only)
> ```

Remove double space

---

*[test/tests.py, line 407 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9#-KsFk6k6FLXX-b0CPnEa:-KsFk6k6FLXX-b0CPnEb:byp18fd) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/8a69036a685300bb0b60e9d4fda331a5b1fea4ef/test/tests.py#L407)):*
> ```Python
> 
>         finally:
>             pass
> ```

Remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9)*

**Comment by mzroth** [comment]
Review status: 1 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[test/tests.py, line 42 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9#-KsFis18VSgwguFI0BGp:-KsFl5V7lzdcHatwvojd:b-896fix) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/8a69036a685300bb0b60e9d4fda331a5b1fea4ef/test/tests.py#L42)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add comment here
</blockquote></details>

Done.

---

*[test/tests.py, line 52 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9#-KsFiqgFD06K00oHzHy7:-KsFl6nWq-c6LcFI6qwh:b-896fix) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/8a69036a685300bb0b60e9d4fda331a5b1fea4ef/test/tests.py#L52)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add comment here
</blockquote></details>

Done.

---

*[test/tests.py, line 151 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9#-KsFjKn_zgZTpt37uoK8:-KsFlCSsWt6ZU2gNZwjK:b-896fix) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/8a69036a685300bb0b60e9d4fda331a5b1fea4ef/test/tests.py#L151)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Change back
</blockquote></details>

Done.

---

*[test/tests.py, line 172 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9#-KsFjeXGAi9d_8Jh47Wv:-KsFlPthFWvQxYKl4JOc:b-79fkcp) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/8a69036a685300bb0b60e9d4fda331a5b1fea4ef/test/tests.py#L172)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

How many times is this used?
</blockquote></details>

6 times

---

*[test/tests.py, line 365 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9#-KsFk-LfYHn668JWq-gr:-KsFluDFjoRbZ3Sr64dO:bvdomqm) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/8a69036a685300bb0b60e9d4fda331a5b1fea4ef/test/tests.py#L365)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove double space
</blockquote></details>

I like my double space

---

*[test/tests.py, line 407 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9#-KsFk6k6FLXX-b0CPnEa:-KsFm-OprqYwTDn96HBf:b-896fix) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/8a69036a685300bb0b60e9d4fda331a5b1fea4ef/test/tests.py#L407)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9)*

**Comment by mzroth** [comment]
Review status: 1 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[test/tests.py, line 292 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9#-KsFjrqHA-jP_fqfQWok:-KsFrlbtLFulIkFJHv-k:b-896fix) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/e1fad372666ca3eeedc206483fb0e96c4f885603/test/tests.py#L292)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Put this back and fix test
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r2.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/9)*

**Pull request merged**
