### PR TITLE
feature/createBracket -> master

### PR DESCRIPTION
**Pull request by mzroth**
This change is [Reviewable](https://reviewable.io/reviews/romrell4/bracket-challenge-ws/1)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/manager.py, line 94 at r2](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/1#-KqjDqPzBcOBmXVflz3W:-KqjDqPzBcOBmXVflz3X:brk9ece) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/e035a0ac9d5d55e63097d984d83949ef16a4d220/src/manager.py#L94)):*
> ```Python
>                 da.create_match(match)
>         return new_bracket["bracket_id"]
>     
> ```

Remove tab

---

*[test/tests.py, line 179 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/1#-KqjDfhADUV-7v9OqI4u:-KqjDfhADUV-7v9OqI4v:b9gjf6m) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/4c795865901f8aa5ccd7a7f7b0b8c9368fde1cc7/test/tests.py#L179)):*
> ```Python
>         assert response["statusCode"] == 412
> 
>         da.delete_tournament(tournament["tournament_id"])
> ```

Put in finally

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/1)*

**Comment by romrell4** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/tests.py, line 181 at r3](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/1#-KqjFYbHlcplmNsfxQrf:-KqjFYbHlcplmNsfxQrg:bx991ui) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/81d52040555ad776c057914a6093f78bcb0deeb1/test/tests.py#L181)):*
> ```Python
> 
>         finally:
>             da.delete_tournament(tournament["tournament_id"])
> ```

Use variable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/1)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/1)*

**Comment by mzroth** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/manager.py, line 94 at r2](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/1#-KqjDqPzBcOBmXVflz3W:-KqjEAV7OUACiW-hov0G:b-896fix) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/e035a0ac9d5d55e63097d984d83949ef16a4d220/src/manager.py#L94)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove tab
</blockquote></details>

Done.

---

*[test/tests.py, line 179 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/1#-KqjDfhADUV-7v9OqI4u:-KqjFNHI6SHCF6sI-tgf:b-896fix) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/4c795865901f8aa5ccd7a7f7b0b8c9368fde1cc7/test/tests.py#L179)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Put in finally
</blockquote></details>

Done.

---

*[test/tests.py, line 181 at r3](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/1#-KqjFYbHlcplmNsfxQrf:-KqjFhTYPk4SzQgqtZ3e:b-896fix) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/81d52040555ad776c057914a6093f78bcb0deeb1/test/tests.py#L181)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Use variable
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/1)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/1)*

**Pull request merged**
