### PR TITLE
feature/batchCreatePlayers -> master

### PR DESCRIPTION
**Pull request by mzroth**
This change is [Reviewable](https://reviewable.io/reviews/romrell4/bracket-challenge-ws/11)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/da.py, line 61 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/11#-KsK4_GRmE2YcdRX_NmO:-KsK4_GRmE2YcdRX_NmP:bvut6cr) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/b77f624ae5621e2608ea6a9c4c1e121c22769a48/src/da.py#L61)):*
> ```Python
>     for player in players:
>         values.append("(%s)")
>         args += [player.get("name")]
> ```

Use .append()

---

*[test/da_tests.py, line 17 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/11#-KsK4uUneGvLaBFwbAt2:-KsK4uUneGvLaBFwbAt3:bkl9i5d) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/b77f624ae5621e2608ea6a9c4c1e121c22769a48/test/da_tests.py#L17)):*
> ```Python
> 
>         # test batch insert of players
>         da.create_players([dict1, dict2])
> ```

Do this above the da.create_players() method:
```python
assert len([player for player in da.get_players() if player["name"].startwith("test")]) == 0
```

---

*[test/tests.py, line 53 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/11#-KsK63N7OUXwpjScRptr:-KsK63N7OUXwpjScRpts:b-pb44rm) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/b77f624ae5621e2608ea6a9c4c1e121c22769a48/test/tests.py#L53)):*
> ```Python
>             # this creates players and appends all their ids to player_ids
>             da.create_players(players)
>             players = da.get_players()
> ```

inline

---

*[test/tests.py, line 447 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/11#-KsK6HptymXRabh78evL:-KsK6HpuVPTMvRiBi9fR:b-pb44rm) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/b77f624ae5621e2608ea6a9c4c1e121c22769a48/test/tests.py#L447)):*
> ```Python
>             players.append({"name": "_player" + str(i + 1)})
>         da.create_players(players)
>         players = da.get_players()
> ```

inline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/11)*

**Comment by mzroth** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/da.py, line 61 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/11#-KsK4_GRmE2YcdRX_NmO:-KsK8t-_84XTcigC3Xhk:b-896fix) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/b77f624ae5621e2608ea6a9c4c1e121c22769a48/src/da.py#L61)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Use .append()
</blockquote></details>

Done.

---

*[test/da_tests.py, line 17 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/11#-KsK4uUneGvLaBFwbAt2:-KsK8tlWTJrqo16dppRt:b-896fix) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/b77f624ae5621e2608ea6a9c4c1e121c22769a48/test/da_tests.py#L17)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do this above the da.create_players() method:
```python
assert len([player for player in da.get_players() if player["name"].startwith("test")]) == 0
```
</blockquote></details>

Done.

---

*[test/tests.py, line 53 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/11#-KsK63N7OUXwpjScRptr:-KsK8uPEzs9YBLQ6DsFL:b-896fix) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/b77f624ae5621e2608ea6a9c4c1e121c22769a48/test/tests.py#L53)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

inline
</blockquote></details>

Done.

---

*[test/tests.py, line 447 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/11#-KsK6HptymXRabh78evL:-KsK8v-SHhqYCFIYsnGR:b-896fix) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/b77f624ae5621e2608ea6a9c4c1e121c22769a48/test/tests.py#L447)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

inline
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/11)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/11)*

**Comment by romrell4** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/11)*

**Pull request merged**
