### PR TITLE
feature/scores -> master

### PR DESCRIPTION
**Pull request by mzroth**
This change is [Reviewable](https://reviewable.io/reviews/romrell4/bracket-challenge-ws/14)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/manager.py, line 160 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/14#-KsQ9ki_J_O9HhyxYxNc:-KsQ9ki_J_O9HhyxYxNd:b2nihh8) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/d3503f64b4e7945fba2b4c53adb252f094eca911/src/manager.py#L160)):*
> ```Python
>         for round in bracket["rounds"]:
>             user_rounds += round
>         for match in range(len(user_rounds)):
> ```

zip

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/14)*

**Comment by romrell4** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[test/tests.py, line 521 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/14#-KsQAQ9vk6GPaHmTHtnE:-KsQAQ9vk6GPaHmTHtnF:b-r8otvu) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/d3503f64b4e7945fba2b4c53adb252f094eca911/test/tests.py#L521)):*
> ```Python
>         rounds = 3
>         master_bracket, player_ids = create_bracket(rounds, True, True)
>         tournament = da.get_tournament(master_bracket["tournament_id"])
> ```

Comment here

---

*[test/tests.py, line 527 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/14#-KsQAHb-aAnQ2G8ir6AO:-KsQAHb-aAnQ2G8ir6AP:b-r8otvu) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/d3503f64b4e7945fba2b4c53adb252f094eca911/test/tests.py#L527)):*
> ```Python
>         full_master_bracket, player_ids = create_bracket(rounds, False, True, player_ids, tournament)
>         full_test_bracket, player_ids = create_bracket(rounds, False, True, player_ids, tournament)
>         test_bracket = get_body(execute("/tournaments/{tournamentId}/brackets/{bracketId}", path_params = {"tournamentId": tournament["tournament_id"], "bracketId": test_bracket["bracket_id"]}))
> ```

Comment here

---

*[test/tests.py, line 540 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/14#-KsQDddiYnIARweDteZx:-KsQDddiYnIARweDteZy:bvbzrjf) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/d3503f64b4e7945fba2b4c53adb252f094eca911/test/tests.py#L540)):*
> ```Python
>             tournament["master_bracket_id"] = full_master_bracket["bracket_id"]
>             da.update_tournament(tournament["tournament_id"], tournament)
>             for round in range(rounds):
> ```

zip here?

---

*[test/tests.py, line 556 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/14#-KsQDlTe00bU71ZnD46p:-KsQDlTe00bU71ZnD46q:b-h4bywy) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/d3503f64b4e7945fba2b4c53adb252f094eca911/test/tests.py#L556)):*
> ```Python
>             body = get_body(response)
>             assert "score" in body
>             score = 0
> ```

Comment about what you're doing here (getting total score for ALL correct)

---

*[test/tests.py, line 557 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/14#-KsQDggSpy1scU1h44jO:-KsQDggSpy1scU1h44jP:b-r4ba9y) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/d3503f64b4e7945fba2b4c53adb252f094eca911/test/tests.py#L557)):*
> ```Python
>             assert "score" in body
>             score = 0
>             for round in range(len(body["rounds"])):
> ```

foreach?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/14)*

**Comment by mzroth** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/manager.py, line 160 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/14#-KsQ9ki_J_O9HhyxYxNc:-KsQ9pscpVS5WKixdI1E:b-896fix) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/d3503f64b4e7945fba2b4c53adb252f094eca911/src/manager.py#L160)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

zip
</blockquote></details>

Done.

---

*[test/tests.py, line 521 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/14#-KsQAQ9vk6GPaHmTHtnE:-KsQErqZSgrVlvm6RzgV:b-896fix) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/d3503f64b4e7945fba2b4c53adb252f094eca911/test/tests.py#L521)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment here
</blockquote></details>

Done.

---

*[test/tests.py, line 527 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/14#-KsQAHb-aAnQ2G8ir6AO:-KsQEsMOjX0N4rVKmuMx:b-896fix) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/d3503f64b4e7945fba2b4c53adb252f094eca911/test/tests.py#L527)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment here
</blockquote></details>

Done.

---

*[test/tests.py, line 540 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/14#-KsQDddiYnIARweDteZx:-KsQHqnN12wLRIwP4oPO:b-896fix) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/d3503f64b4e7945fba2b4c53adb252f094eca911/test/tests.py#L540)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

zip here?
</blockquote></details>

Done.

---

*[test/tests.py, line 556 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/14#-KsQDlTe00bU71ZnD46p:-KsQFJq5VJdGIwArNfj6:b-896fix) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/d3503f64b4e7945fba2b4c53adb252f094eca911/test/tests.py#L556)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment about what you're doing here (getting total score for ALL correct)
</blockquote></details>

Done.

---

*[test/tests.py, line 557 at r1](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/14#-KsQDggSpy1scU1h44jO:-KsQFKEKvsDPwojTLcPf:bvhbndl) ([raw file](https://github.com/romrell4/bracket-challenge-ws/blob/d3503f64b4e7945fba2b4c53adb252f094eca911/test/tests.py#L557)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

foreach?
</blockquote></details>

I didn't do a for each because I wanted round to be an integer  for the math 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/14)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/romrell4/bracket-challenge-ws/14)*

**Pull request merged**
